### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Lange** [Kegsay/flow-jsdoc#2]
When I run the following command on a fresh checkout of [nodecg/nodecg](https://github.com/nodecg/nodecg):
```
flow-jsdoc -d ./lib -o ./annotated
```

I receive the following error output:
```
C:\Users\vanca\Documents\Programming\nodecg\0.8>flow-jsdoc -d ./lib -o ./annotated
C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:90
                    throw err0;
                    ^

RangeError: Maximum call stack size exceeded
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\vanca\AppData\Roaming\npm\node_modules\flow-jsdoc\node_modules\mkdirp\index.js:78:17)
```

It seems to make the `annotated` folder then encounter this error.

Let me know if there's any further testing you'd like me to do to try to narrow down the problem.

**Comment by Kegsay** [comment]
Hmm, I doubt that the stack is genuinely being exceeded on that project (but hey, you never know!).

I suspect this is probably https://github.com/substack/node-mkdirp/issues/40 - Which OS are you using?

**Comment by Lange** [comment]
I am running Windows 10 64 bit (Anniversary Update).

**Comment by Kegsay** [comment]
Running on [WSL](https://msdn.microsoft.com/en-gb/commandline/wsl/about), Cygwin or native (cmd)?

**Comment by Lange** [comment]
I am running in a native Windows command prompt.

**Comment by Kegsay** [comment]
Can repro. Will keep you posted.

**Comment by Kegsay** [comment]
Fixed in https://github.com/Kegsay/flow-jsdoc/commit/081b074c106e54abb3bc971afb0e170a094732ec

It looks like the project you linked to is using certain [class properties](https://github.com/nodecg/nodecg/blob/master/lib/browser/replicant.js#L364) which Esprima doesn't know how to parse, which is unfortunate. Rather than bailing, I'll add a `--skip` option to skip over files which cannot be parsed correctly.

**Comment by Kegsay** [comment]
Added `--skip`, this project works now:
```
$ flow-jsdoc -d lib/ -o annotated --skip
/home/kegsay/github/nodecg/lib/api.js
/home/kegsay/github/nodecg/lib/assets/AssetFile.js
/home/kegsay/github/nodecg/lib/assets/index.js
/home/kegsay/github/nodecg/lib/browser/config.js
/home/kegsay/github/nodecg/lib/browser/dist/browserifiedApi.min.js
/home/kegsay/github/nodecg/lib/browser/dist/browserifiedTestApi.js
/home/kegsay/github/nodecg/lib/browser/index.js
/home/kegsay/github/nodecg/lib/browser/logger.js
/home/kegsay/github/nodecg/lib/browser/replicant.js
    Failed to parse: Error: Line 365: Unexpected token }
/home/kegsay/github/nodecg/lib/bundles.js
/home/kegsay/github/nodecg/lib/config/index.js
/home/kegsay/github/nodecg/lib/config/loader.js
/home/kegsay/github/nodecg/lib/dashboard/index.js
/home/kegsay/github/nodecg/lib/dashboard/public/dashboard.js
/home/kegsay/github/nodecg/lib/dashboard/public/dialog_helper.js
/home/kegsay/github/nodecg/lib/dashboard/public/dialog_opener.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-asset-file.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-assets.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-dashboard-panel-info-dialog.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-dashboard-panel.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-dialog.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-single-instance.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-sound-cue.js
/home/kegsay/github/nodecg/lib/dashboard/public/elements/ncg-sounds.js
/home/kegsay/github/nodecg/lib/dashboard/public/panel_packery.js
/home/kegsay/github/nodecg/lib/dashboard/public/single_instances.js
/home/kegsay/github/nodecg/lib/graphics/index.js
/home/kegsay/github/nodecg/lib/graphics/single_instance/index.js
/home/kegsay/github/nodecg/lib/graphics/single_instance/public/client_heart.js
/home/kegsay/github/nodecg/lib/logger.js
/home/kegsay/github/nodecg/lib/login/index.js
/home/kegsay/github/nodecg/lib/login/public/QueryString.js
/home/kegsay/github/nodecg/lib/login/tokens.js
/home/kegsay/github/nodecg/lib/login/UnauthorizedError.js
/home/kegsay/github/nodecg/lib/replicant/index.js
/home/kegsay/github/nodecg/lib/replicant/replicant.js
/home/kegsay/github/nodecg/lib/replicant/shared.js
/home/kegsay/github/nodecg/lib/replicator.js
/home/kegsay/github/nodecg/lib/server/extensions.js
/home/kegsay/github/nodecg/lib/server/index.js
/home/kegsay/github/nodecg/lib/sounds.js
/home/kegsay/github/nodecg/lib/util/authcheck.js
/home/kegsay/github/nodecg/lib/util/debounce-name.js
/home/kegsay/github/nodecg/lib/util/index.js
/home/kegsay/github/nodecg/lib/util/injectscripts.js
```

**Comment by Lange** [comment]
Thanks!

And yeah this is not the first tool that has had a hard time dealing with my use of static properties, I should really just use a getter there.
